### ISSUE TITLE
WP Keyring plugin only showing 1 service, Not showing other services

### ISSUE THREAD

**Issue by buysellwill** [beaulebens/keyring#112]
only showing 1 service in add-connection:

The following services need to be configured correctly before you can connect to them.

[500px]

Check here: https://prnt.sc/bTvvKQ-JVENS

I want to use google mail service, but its not there to connect, only showing 1.

**Comment by mdrovdahl** [comment]
Probably related to https://github.com/beaulebens/keyring/pull/109

**Comment by marekhrabe** [comment]
+1 here. I'm not sure what the root cause but my social importers and Keyring integrations have all stopped working this week. 

All my existing connections for services like Strava or Foursquare now identify themselves as 500px at /tools.php?page=keyring

![Screenshot 2023-11-16 at 17 53 08](https://github.com/beaulebens/keyring/assets/156676/87a4e251-efcc-4f57-ba57-085340d7d254)

and similarly, all keyring importer screens (/admin.php?import=strava for example) show up as Delicious importer, regardless of the service selection

![Screenshot 2023-11-16 at 18 09 05](https://github.com/beaulebens/keyring/assets/156676/ae930f10-dd48-488b-a277-6f62447bf781)

I haven't had time to dig deeper yet, only tried to quickly install an older version of the plugin which didn't help with any of those two issues. However, switching the site from PHP 8.1 to 7.4 did fix the issue, so it truly looks like a compat issue.

I'm running WP 6.4.1 on Pressable, and experiencing this issue only together with PHP 8.1, while PHP 7.4 works well.

**Comment by beaulebens** [comment]
This should be working if you use the trunk version of both Keyring and Keyring Social Importers now. I made a similar change to remove a singleton in https://github.com/beaulebens/keyring-social-importers/commit/2af57785d3887784ccf72a44d66fe98e68c0a6ba

**Comment by mtausig** [comment]
I'm afraid this issue is back. I have the same problem on PHP 8.2 and Wordpress 6.6.1.
